### ISSUE TITLE
--gmt_file

### ISSUE THREAD

**Issue by MIAO0916** [opain/TWAS-GSEA#2]
hi ！@opain
In --gmt_file, You said that An example can be found here, but i didn't find it.
Is it in http://www.gsea-msigdb.org/gsea/downloads.jsp?
If sure ,which one should I use? ZIPped Human MSigDB file set? Individual Human Gene Annotations Files?or ZIPped Human Gene Annotations file set?

Thanks !

**Comment by opain** [comment]
Hi, 

MSigDB is a good source of gene set data. 

I prefer to download specific collections from this page: http://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp

Which gene set you include in your analysis is up to you. Commonly used collections are 'C2: curated gene sets' and 'C5: ontology gene sets'.

On the right of each collection, you can download the .gmt file. You can select which gene IDs you want the .gmt to contain (e.g. HGNC gene symbols, or Entrez IDs).

![Screenshot 2023-01-07 102314](https://user-images.githubusercontent.com/43761992/211145667-a0b0fe20-042a-480c-a0ed-c88db7010aaa.png)

I hope this helps!
