### ISSUE TITLE
TWAS-GSEA from non-FUSION TWAS?

### ISSUE THREAD

**Issue by mooreann** [opain/TWAS-GSEA#9]
Hi there!

I'm trying to see if its possible to run TWAS-GSEA with results from a TWAS method other than FUSION (ie PrediXcan).  I've modified my output files to match the examples shown. The biggest concern I have is not having a MODELCV.R2 column with real filenames in the TWAS results file from FUSION which the documentation mentioned was used to “to retain the best feature for each gene” from the FUSION models. Are those features essential or is that something I can create myself too? 

These my current headers for all files:
TWAS results file
FILE    ID      P0      P1      TWAS.Z  TWAS.P
ENSG00000149474.13      KAT14   18138118        18188387        8.649604458232101       5.445703547135566e-18
ENSG00000102710.19      SUPT20H 37009312        37059713        6.105425097662033       1.039053001926219e-09

position file
WGT     ID      CHR     P0      P1
ENSG00000223972.5       DDX11L1 1       11869   14409
ENSG00000227232.5       WASH7P  1       14404   29570

expression ref file
FID     IID     ENSG00000238009.6       ENSG00000187642.9       ENSG00000187608.8       ENSG00000186891.13 ...

Here is my input command:
Rscript TWAS-GSEA.V1.2.R --twas_results Whole_Blood_assoc.gsea_in.txt --pos gencode.v26.loc.twas_gsea --gmt_file msigdb_v2023.2.Hs_files_to_download_locally/msigdb_v2023.2.Hs_GMTs/c1.all.v2023.2.Hs.symbols.gmt --expression_ref ./Whole_Blood_predict.txt --output demo

Currently when I run this I get the following error, which is hard to figure out where the issue is:
Error in do.call(paste, c(tmp[, (dim(tmp)[2] - 1):dim(tmp)[2]], sep = "/")) : 
  second argument must be a list
Calls: do.call -> do.call
Execution halted

Any insight would be helpful. Thanks in advance!

**Comment by opain** [comment]
Hi,

I have not tried using TWAS-GSEA with PrediXcan output, although it is possible.

The MODELCV.R2 column is used to select the feature best predicting each gene. So if a given gene ID is duplicated, then it will select the feature that has the highest MODELCV.R2. If you only have one feature for each gene (i.e. no duplicated gene IDs in your data), then you can set the MODELCV.R2 column to NA, and specify '--allow_duplicate_ID TRUE' when running TWAS-GSEA.

The error you are getting is because the FILE column typically contains a path like 'CMC.BRAIN.RNASEQ/CMC.LOC643837.wgt.RDat', which points to the model that was used for the TWAS. The script fails because your file doesn't contain a '/' character. As a solution, I would suggest adding something like 'weight/' to your FILE column, e.g. 'weight/ENSG00000149474.13'. This should avoid the error.

The format of your other files looks good.

Let me know if this doesn't work and we can try and find another solution. 

Ollie

**Comment by mooreann** [comment]
Thanks so much for your quick response!

Here's the updated headers of changed files (I also added the .wgt.Rdat to try to match as close as possible since that seemed to eliminate an additional warning):

TWAS results file 
FILE    ID      P0      P1      TWAS.Z  TWAS.P  MODELCV.R2
weight/ENSG00000149474.13.wgt.RDat      KAT14   18138118        18188387        8.649604458232101       5.445703547135566e-18   
weight/ENSG00000102710.19.wgt.RDat      SUPT20H 37009312        37059713        6.105425097662033       1.039053001926219e-09   

position file
WGT     ID      CHR     P0      P1
weight/ENSG00000223972.5.wgt.RDat       DDX11L1 1       11869   14409
weight/ENSG00000227232.5.wgt.RDat       WASH7P  1       14404   29570

Heres my input command:
Rscript ./TWAS-GSEA.V1.2.R --twas_results ./Whole_Blood_assoc.gsea_in.test.txt --allow_duplicate_ID TRUE --pos ./gencode.v26.loc.twas_gsea.test --gmt_file ./msigdb_v2023.2.Hs_files_to_download_locally/msigdb_v2023.2.Hs_GMTs/c1.all.v2023.2.Hs.symbols.gmt --expression_ref ./Whole_Blood_predict.txt --output demo

However, now the error I receive is:
Error in Linear_Results[order(Linear_Results$P), ] : 
  incorrect number of dimensions
Execution halted

Could this be missing columns in the results file? Or a gene name mismatch somewhere else?

**Comment by opain** [comment]
Can you send me the .log file from TWAS-GSEA? It might contain clues as to why the script failed. It will be called 'demo.log'

**Comment by mooreann** [comment]
I was able to figure it out! Mainly the gmt file I was using before used gene symbols but replacing it with the entrez ID one like you specified in the documentation fixed the issue! So it is officially up and working with PrediXcan outputs!

Thanks so much for all your help!

**Comment by opain** [comment]
That’s great!

Yes, by default the TWAS IDs are assumed to be gene symbols, and the gmt IDs to be entrez IDs. The script will then try and match them using biomart.

Alternatively, the --use_alt_id flag can be used to select a TWAS column to use for matching with the gmt file. For example, if your gmt file had gene symbols, and so did the TWAS, then ‘--use_alt_id ID’ would have worked.
